name: Linux
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: 
        #  - x86_64
         - aarch64
        #  - armv7l
    steps:
      - uses: actions/checkout@v4
      - name: Setup QEMU User and binfmt
        uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = ${{ matrix.system }}-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # Isolate the environment with "nix shell -i" to avoid LD_LIBRARY_PATH issues
      - run: nix shell -i nixpkgs#bash --command bash -l -c "nix flake check --system ${{ matrix.system }}-linux --accept-flake-config"