name: Linux
on:
  push:
  pull_request:

env:
  # https://github.com/NixOS/nix/issues/8608
  LD_LIBRARY_PATH: ""

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup QEMU User and binfmt
        uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = ${{ matrix.system }}-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --system ${{ matrix.system }}-linux --accept-flake-config